AWSTemplateFormatVersion: '2010-09-09'
Description: Website client of Fortune API

Parameters:

  BucketName:
    Type: String
    Description: The name for bucket.
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)

Resources:

  # Empty Bucket to hold static stuff
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

Outputs:
  BucketName:
    Value: !Ref WebsiteBucket
    Description: S3 bucket to hold website content
