AWSTemplateFormatVersion: '2010-09-09'
Description: Website client of Fortune API

Parameters:

  BucketName:
    Type: String
    Description: The name for bucket.
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)

Resources:

  # Empty Bucket to hold static webpage
  # We set access control to private so users need to access via CloudFront CDN.
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Cloudfront to S3 origin access identity"

  # Cloudfront distribution fronting the S3 website
  FrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - WebsiteBucket
    - OriginAccessIdentity
    Properties:
      DistributionConfig:
        Comment: Fortune Website
        Enabled: "true"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: myS3Origin
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          MinTTL: "0"
          MaxTTL: "0"
          DefaultTTL: "0"
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: all
          ViewerProtocolPolicy: allow-all
        Origins:
          # Origin from S3 website
          - Id: myS3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: Grant a CloudFront Origin Identity access to support private content
            Action: "s3:GetObject"
            Effect: "Allow"
            Principal:
             CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"

Outputs:
  BucketName:
    Value: !Ref WebsiteBucket
    Description: S3 bucket to hold website content
  DomainName:
    Value: !GetAtt [FrontDistribution, DomainName]
    Description: DomainName of Cloudfront distribution
  Distribution:
    Value: !Ref FrontDistribution
    Description: Cloudfront distribution.
